ansible_authorized_keys: "https://ssh.megaphonetech.com/megaphonetech.pub"
ansible_python_interpreter: /usr/bin/python3
# fail2ban greenlist
greenlist_ips:
  - 69.122.128.206
#CiviCRM extension blacklist
extension_blacklist:
  - none

#Icinga2
primary_icinga_server: 'orange.megaphonetech.com'
primary_icinga_server_ip: '173.255.234.245'
apache_remove_default_vhost: true
#temp for Apache
apache_vhosts: []
#PHP
php_version: '7.4'
php_default_version_debian: '7.4'
php_versions_install_recommends: true
php_packages_extra:
  - php-pear
  - php{{ php_version }}-gd
  - php-imagick
  - php{{ php_version }}-mysql
  - php{{ php_version }}-imagick
  - php{{ php_version }}-bcmath
  - php{{ php_version }}-curl
  - php{{ php_version }}-sqlite3
  - php{{ php_version }}-mbstring
  - php{{ php_version }}-xml
  - php{{ php_version }}-zip
  - php{{ php_version }}-intl
  - php{{ php_version }}-gmp
  - php{{ php_version }}-bz2
  - php{{ php_version }}-soap

php_memory_limit: '128M'
php_max_execution_time: 300
php_post_max_size: '128M'
php_max_input_vars: "20000"
php_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE" 
php_enable_php_fpm: true
php_fpm_listen: "/var/run/php/php-fpm.sock"
#Workaround for https://github.com/geerlingguy/ansible-role-php/issues/255
#php_extension_conf_paths: '/etc/php/7.0/mods-available'
#MySQL
mysql_root_password: "{{ lookup('passwordstore', client + '/' + hostname + '/mysql/root create=true length=32') }}"
sqldumps_path: "{{ webroot }}/../sql-dumps"

# MySQL tunings
mysql_group_concat_max_len: "15000"
mysql_tmp_table_size: 128M 
mysql_max_heap_table_size: 128M
mysql_innodb_log_file_size: "512M"

users:
  Jon:
    name: jon
    shell: "/bin/zsh"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/jon') }}"
    authorized:
      - https://ssh.megaphonetech.com/jon_id_rsa.pub
    hasdotfiles: true
    oh-my-zsh: true
    dotfiles: https://github.com/MegaphoneJon/dotfiles.git
  Brienne:
    name: brienne 
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/brienne') }}"
    authorized:
      - https://ssh.megaphonetech.com/brienne_id_rsa.pub
    hasdotfiles: false
# deploy-site
monitoring_user: monitor
monitoring_email: jon+monitor@megaphonetech.com
# backup
rsyncnet_user: "8139"
rsyncnet_server: "usw-s008.rsync.net"
# basic auth for test sites
basic_auth_name: "megaphone"
basic_auth_password: "megaphone"
