apache_vhosts: []
php_packages_extra:
  - php-pear
  - php-gd
  - php-imagick
  - php-mysql
  - php-curl
  - php-sqlite3
  - php-opcache
  - php-mbstring

php_max_execution_time: 300
php_post_max_size: '128M'
php_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE" 
php_enable_php_fpm: true
