---
# Run this role BEFORE the postfix role.
- name: Set Postfix to allow incoming
  set_fact:
    postfix_inet_interfaces: all
    smtp_firewall_opening: present
  when: incoming_email == '1'

- name: Set Postfix to deny incoming
  set_fact:
    postfix_inet_interfaces: localhost
    smtp_firewall_opening: absent
  when: incoming_email == '0'

- name: Open port 25 incoming
  iptables:
    chain: INPUT
    destination_port: 25
    protocol: tcp
    jump: ACCEPT
    state: "{{ smtp_firewall_opening }}"
    ip_version: "{{ item }}"
  with_items:
    - ipv4
    - ipv6
  notify: save iptables
  when: incoming_email == '1'

- name: Open to port 25 incoming
  iptables:
    chain: OUTPUT
    ctstate: ESTABLISHED
    source_port: 25
    protocol: tcp
    jump: ACCEPT
    state: "{{ smtp_firewall_opening }}"
    ip_version: "{{ item }}"
  with_items:
    - ipv4
    - ipv6
  notify: save iptables
  when: incoming_email == '1'
