db_host: 127.0.0.1
local_borg_dir: /var/backups/borg
additional_users:
  Noah:
    name: noah
    shell: "/bin/zsh"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('community.general.passwordstore', 'megaphone/ansible/users/noah') }}"
    authorized:
      - https://ssh.megaphonetech.com/noah_id_rsa.pub
    hasdotfiles: false
outgoing_ports:
  - { port: 22, protocol: tcp, name: 'SSH' }
  - { port: 25, protocol: tcp, name: 'SMTP' }
  - { port: 80, protocol: tcp, name: 'HTTP' }
  - { port: 123, protocol: udp, name: 'NTP' }
  - { port: 443, protocol: tcp, name: 'HTTPS' }
  - { port: 465, protocol: tcp, name: 'SMTPS' }
  - { port: 587, protocol: tcp, name: 'SMTP TLS' }
  - { port: 5665, protocol: tcp, name: 'Icinga2' }
  - { port: 10022, protocol: tcp, name: 'Megaphone git SSH', state: absent }
  - { port: 53, protocol: udp, name: 'DNS' }
  - { port: 993, protocol: tcp, name: 'IMAPS' }
  - { port: "{{ security_ssh_port }}", protocol: tcp, name: 'Alternate SSH port' }
  - { port: 3306, protocol: tcp, name: 'SSH in Docker' }
