php_version: '8.1'
local_borg_dir: /var/backups/borg
additional_users:
  Noah:
    name: noah
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/noah') }}"
    authorized:
      - https://ssh.megaphonetech.com/noah_id_rsa.pub
    hasdotfiles: false
