local_borg_dir: /var/backups/borg
additional_users:
  Maya:
    name: maya
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('community.general.passwordstore', 'megaphone/ansible/users/maya') }}"
    authorized:
      - https://ssh.megaphonetech.com/maya_id_rsa.pub
    hasdotfiles: false

