additional_users:
  Eric:
    name: eric
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/eric') }}"
    authorized:
      - https://ssh.megaphonetech.com/eric_id_rsa.pub
    hasdotfiles: false
  Vijay:
    name: vijay
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/vijay') }}"
    authorized:
      - https://ssh.megaphonetech.com/vijay_id_rsa.pub
    hasdotfiles: false
