---
# This provisions any VPSes that were defined but not built in server-list
- hosts: vps
  become: yes

  tasks:
  - name: apt dist-upgrade everyone
    apt:
      name: "*"
      state: latest
      autoremove: yes
      update_cache: yes
    when: contract_type is defined and contract_type is search("VPS")
    register: aptresults

  - name: Show upgraded packages
    debug:
      msg: "{{ aptresults.stdout_lines[8:11] }}"
    when: aptresults.changed == true
