---
- hosts: vps
  become: yes

  roles:
    - { role: common, tags: common }
    - { role: users, tags: users }
    - { role: backupninja, tags: [backup, backupninja] }
    - { role: rsyncnet, tags: [backup, rsyncnet] }
    - { role: firewall-common, tags: firewall }

- hosts: lamp
  become: yes

  roles:
    - { role: contrib/geerlingguy.apache, tags: [apache, deploy-site] }
    - { role: cv, tags: cv }
    - { role: contrib/geerlingguy.mysql, tags: mysql }
    - { role: mysql-additional, tags: [mysql, mysql-additional] }
    - { role: contrib/geerlingguy.php-versions , tags: [php, php-versions] }
    - { role: contrib/geerlingguy.php , tags: php }
    - { role: contrib/geerlingguy.apache-php-fpm , tags: php }
    - { role: php-additional , tags: php }
    - { role: apache-additional , tags: [apache, apache-additional] }
    - { role: contrib/geerlingguy.composer, tags: composer}
    - { role: drush, tags: drush}
    - { role: wp-cli, tags: wp-cli}
    - { role: contrib/geerlingguy.security, tags: security }
    - { role: incoming-smtp, tags: postfix } # Must run before geerlingguy.postifx
    - { role: contrib/geerlingguy.postfix, tags: postfix }
    - { role: fail2ban, tags: fail2ban}
    - { role: modsecurity, tags: modsecurity}
    - { role: mysql-firewall, tags: mysql-firewall}
    - { role: contrib/geerlingguy.docker, tags: docker}
    - { role: contrib/geerlingguy.pip, tags: [docker, pip] }
    - { role: promtail-docker, tags: promtail}

- hosts: training
  become: yes

  roles:
    - { role: contrib/geerlingguy.apache, tags: [apache, deploy-site] }
    - { role: cv, tags: cv }
    - { role: contrib/geerlingguy.mysql, tags: mysql }
    - { role: mysql-additional, tags: [mysql, mysql-additional] }
    - { role: contrib/geerlingguy.php-versions , tags: [php, php-versions] }
    - { role: contrib/geerlingguy.php , tags: php }
    - { role: contrib/geerlingguy.apache-php-fpm , tags: php }
    - { role: php-additional , tags: php }
    - { role: apache-additional , tags: [apache, apache-additional] }
    - { role: contrib/geerlingguy.composer, tags: composer}
    - { role: drush, tags: drush}
    - { role: wp-cli, tags: wp-cli}
    - { role: contrib/geerlingguy.security, tags: security }
    - { role: incoming-smtp, tags: postfix } # Must run before geerlingguy.postifx
    - { role: contrib/geerlingguy.postfix, tags: postfix }
    - { role: fail2ban, tags: fail2ban}
    - { role: php-xdebug, tags: [xdebug, php-xdebug]}
    - { role: civix, tags: civix }
    - { role: civicrm-buildkit, tags: civicrm-buildkit }

- hosts: websites
  become: "{{ 'no' if run_as_user == ansible_user else ('no' if 'mayfirst_ng_site' in group_names else 'yes') }}"
  roles:
    - { role: site-dns, tags: [site-dns] }
    - { role: site-user-php-apache, tags: [site-upa], when: run_as_user != ansible_user and 'mayfirst_ng_site' not in group_names }
    - { role: site-mysql, tags: [site-mysql], when: run_as_user != ansible_user and 'mayfirst_ng_site' not in group_names }
    - { role: site-gitea, tags: [site-gitea] }
    - { role: deploy-site, tags: [site-main] }
    - { role: site-db-sync-initial, tags: [site-db-sync-initial] }
    - { role: site-permissions, tags: [site-permissions]}
    - { role: site-postinstall-config, tags: [site-postinstall-config] }
    - { role: site-standard-extensions, tags: [site-standard-extensions]}
    - { role: site-wp-monitor, tags: [site-wp-monitor] }
    - { role: site-drupal-monitor, tags: [site-drupal-monitor] }
    - { role: site-cron, tags: [site-cron], when: run_as_user != ansible_user and 'mayfirst_ng_site' not in group_names }
    - { role: site-robots-txt, tags: [site-robots-txt] }
    - { role: nosudo-backup, tags: [backup, nosudo-backup], when: run_as_user == ansible_user or 'mayfirst_ng_site' in group_names }
#    - { role: monitoring, tags: monitoring }

- hosts: vps
  become: "{{ 'no' if run_as_user|default('', True) == ansible_user else 'yes' }}"
  roles:
    # Run after deploy-site now that it monitors sites
    - { role: icinga2-satellite, tags: [icinga2, icinga2-satellite] }
    - { role: icinga2-primary, tags: [icinga2, icinga2-primary] }

- hosts: localhosts
  become: yes
  roles:
    - common
    - { role: contrib/geerlingguy.apache, tags: apache }
    - { role: contrib/geerlingguy.mysql, tags: mysql }
    - { role: mysql-additional, tags: mysql }
    - { role: contrib/geerlingguy.php-versions , tags: [php, php-versions] }
    - { role: contrib/geerlingguy.php , tags: php }
    - { role: contrib/geerlingguy.apache-php-fpm , tags: php }
    - { role: php-additional , tags: php }
    - { role: apache-additional , tags: [apache, apache-additional] }
    - { role: contrib/geerlingguy.composer, tags: composer}
    - { role: drush, tags: drush}
    - { role: wp-cli, tags: wp-cli}
    - { role: cv, tags: cv }
    - { role: contrib/geerlingguy.mailhog, tags: mailhog }
    - { role: contrib/geerlingguy.postfix, tags: postfix }
    - { role: mailhog-postfix, tags: mailhog-postfix }
    - { role: backupninja, tags: [backup, backupninja] }
    - { role: rsyncnet, tags: [backup, rsyncnet] }
    - { role: modsecurity, tags: modsecurity}

- hosts: nosudo
  become: no
  gather_facts: no
  roles:
    - { role: cv, tags: cv }
    - { role: rsyncnet, tags: [backup, rsyncnet] }
    - { role: icinga2-primary, tags: [icinga2, icinga2-primary] }

- hosts: redis
  become: yes
  roles:
    - { role: contrib/geerlingguy.redis, tags: redis }
    - { role: redis-additional, tags: redis }
