---
# This provisions any VPSes that were defined but not built in server-list
- import_playbook: provision.yml
- hosts: vps
  become: yes

  roles:
    - common
    - mtcusers

- hosts: lamp
  become: yes

  roles:
    - { role: firewall-common, tags: firewall }
    - { role: contrib/geerlingguy.apache, tags: apache }
    - icinga2
    - { role: contrib/geerlingguy.composer, tags: composer}
    - drush
    - cv

- hosts: testgroup
  become: yes
  roles:
    - { role: contrib/geerlingguy.mysql, tags: mysql }
    - { role: contrib/geerlingguy.php , tags: php }
    - { role: contrib/geerlingguy.apache-fpm-php , tags: php }
    - { role: php-additional , tags: php }
    - wp-cli
    - { role: contrib/geerlingguy.security, tags: security }
