---
# This provisions any VPSes that were defined but not built in server-list
- import_playbook: provision.yml
- hosts: vps
  become: yes

  roles:
    - common
    - { role: users, tags: users }

- hosts: lamp
  become: yes

  roles:
    - { role: firewall-common, tags: firewall }
    - { role: contrib/geerlingguy.apache, tags: apache, deploy-site }
    - { role: cv, tags: cv }
    - { role: contrib/geerlingguy.mysql, tags: mysql }

- hosts: testgroup
  become: yes
  roles:
    - { role: contrib/geerlingguy.php-versions , tags: php }
    - { role: contrib/geerlingguy.php , tags: php }
    - { role: contrib/geerlingguy.apache-php-fpm , tags: php }
    - { role: php-additional , tags: php }
    # these next two are certified for use in the lamp group buy depend on php which isn't.
    - { role: contrib/geerlingguy.composer, tags: composer}
    - { role: drush, tags: drush}
    - { role: wp-cli, tags: wp-cli}
    - { role: contrib/geerlingguy.security, tags: security }
    - { role: incoming-smtp, tags: postfix } # Must run before geerlingguy.postifx
    - { role: contrib/geerlingguy.postfix, tags: postfix }
    - { role: backupninja, tags: backup }
    - { role: rsyncnet, tags: backup }

- hosts: websites
  become: yes
  roles:
    - { role: deploy-site, tags: deploy-site }

- hosts: testgroup
  become: yes
  roles:
    # Run after deploy-site now that it monitors sites
    - { role: icinga2-satellite, tags: [icinga2, icinga2-satellite] }
    - { role: icinga2-primary, tags: [icinga2, icinga2-primary] }

- hosts: localhosts
  become: yes
  roles:
    - common
    - { role: contrib/geerlingguy.apache, tags: apache }
    - { role: contrib/geerlingguy.php , tags: php }
    - { role: contrib/geerlingguy.apache-php-fpm , tags: php }
    - { role: php-additional , tags: php }
    - wp-cli
    - { role: cv, tags: cv }

- hosts: nosudo
  become: no
  gather_facts: no
  roles:
    - { role: icinga2-primary, tags: [icinga2, icinga2-primary] }
