---
# This provisions any VPSes that were defined but not built in server-list
- import_playbook: provision.yml
- hosts: vps
  become: yes

  roles:
    - common
    - mtcusers

- hosts: lamp
  become: yes

  roles:
    - { role: firewall-common, tags: firewall }
    - { role: contrib/geerlingguy.apache, tags: apache }
    - icinga2
    - cv

- hosts: testgroup
  become: yes
  roles:
    - { role: contrib/geerlingguy.mysql, tags: mysql }
    - { role: contrib/geerlingguy.php , tags: php }
    - { role: contrib/geerlingguy.apache-fpm-php , tags: php }
    - { role: php-additional , tags: php }
    # these next two are certified for use in the lamp group buy depend on php which isn't.
    - { role: contrib/geerlingguy.composer, tags: composer}
    - drush
    - wp-cli
    - { role: contrib/geerlingguy.security, tags: security }
    - { role: incoming-smtp, tags: postfix }
    - { role: contrib/geerlingguy.postfix, tags: postfix }
    - { role: backupninja, tags: backup }
    - { role: apache-vhosts, tags: [apache,apache-vhosts] }
