---
- name: Provision VMs
  hosts: vps:localhosts
  vars:
    ansible_user: root
  gather_facts: no
  connection: local

  roles:
    - { role: provision-linode, tags: provision }
    - { role: bootstrap, tags: bootstrap }
