---
- hosts: websites
  become: yes
  become_user: "{{ run_as_user }}"

  tasks:
  - name: Shut up about Civi extensions (warnings only, 7 days)
    command: "cv --cwd='{{ webroot }}' api StatusPreference.create ignore_severity=3 name='checkExtensionsUpdates' hush_until='{{ '%Y-%m-%d' | strftime( ( ansible_date_time.epoch | int ) + ( 86400 * 7 )  ) }}'" 
    when: civicrm == 'Yes'
    tags: civi-extensions

  - name: Shut up about Civi core updates (warnings only, 7 days)
    command: "cv --cwd='{{ webroot }}' api StatusPreference.create ignore_severity=3 name='checkVersion_upgrade' hush_until='{{ '%Y-%m-%d' | strftime( ( ansible_date_time.epoch | int ) + ( 86400 * 7 )  ) }}'" 
    when: civicrm == 'Yes'
    tags: civi-core

  - name: Collect last 10 errors in watchdog
    command: "drush --root='{{ webroot }}' watchdog:show --severity=3"
    when: cms == 'Drupal' or cms == 'Drupal8'
    register: drushmessages
    tags: clear-drush, show-drush
    changed_when: false
  
  - name: Show last 10 errors in watchdog
    debug:
      var: drushmessages.stdout
    tags: clear-drush, show-drush
    changed_when: false

  - name: Clear errors in watchdog
    command: "drush --yes --root='{{ webroot }}' watchdog:delete --severity=3"
    when: cms == 'Drupal' or cms == 'Drupal8' and drushmessages.stdout != ''
    tags: clear-drush