---
- hosts: websites_test:websites_live
  # become: yes
  # become_user: "{{ run_as_user }}"
  gather_facts: no

  vars:
    ajaxDict:
      drupal: civicrm/ajax/rest
      drupal8: civicrm/ajax/rest
      backdrop: civicrm/ajax/rest
      wordpress: civicrm/ajax/rest
      joomla: administrator/components/com_civicrm/civicrm/extern/rest.php
    endpoint: '{{ ajaxDict[cms | lower] }}'
    crm_api_key: "{{ lookup('passwordstore', client + '/' + (canonical_hostname | default(hostname, true)) + '/' + (canonical_bare_url | default(bare_url, true)) + '/civicrm_api_key') }}"
    crm_site_key: "{{ lookup('passwordstore', client + '/' + hostname + '/' + bare_url + '/sitekey') }}"
    seven_days_hence: "{{ '%Y-%m-%d' | strftime( (lookup('pipe', 'date +%s') | int) + ( 86400 * 7 ) ) }}"

  tasks:

  - name: Shut up about Civi extensions (warnings only, 7 days)
    uri:
      url: "{{ primary_url }}/{{ endpoint }}"
      method: POST
      body:
        entity: StatusPreference
        action: create
        json: "{{ {'name': item, 'ignore_severity': 3, 'hush_until': seven_days_hence } | to_json }}"
        api_key: "{{ crm_api_key }}"
        key: "{{ crm_site_key }}"
      body_format: form-urlencoded
      url_username: "{{ (env == 'Test') | ternary('megaphone', '') }}"
      url_password: "{{ (env == 'Test') | ternary('megaphone', '') }}"
    with_items:
      - checkExtensionsUpdates
      - allavailableupgrades
    delegate_to: 127.0.0.1
    when: civicrm == 'Yes'
    tags: civi-extensions

  # - name: Shut up about Civi extensions (allavailableupgrades) (warnings only, 7 days)
  #   uri:
  #     url: "{{ primary_url }}/{{ endpoint }}"
  #     method: POST
  #     body:
  #       entity: StatusPreference
  #       action: create
  #       json: "{{ {'name': 'allavailableupgrades', 'ignore_severity': 3, 'hush_until': seven_days_hence } | to_json }}"
  #       api_key: "{{ crm_api_key }}"
  #       key: "{{ crm_site_key }}"
  #     body_format: form-urlencoded
  #     url_username: "{{ (env == 'Test') | ternary('megaphone', '') }}"
  #     url_password: "{{ (env == 'Test') | ternary('megaphone', '') }}"
  #   delegate_to: 127.0.0.1
  #   when: civicrm == 'Yes'
  #   tags: civi-extensions

  - name: Shut up about Civi core updates (warnings only, 7 days)
    uri:
      url: "{{ primary_url }}/{{ endpoint }}"
      method: POST
      body:
        entity: StatusPreference
        action: create
        json: "{{ {'name': item, 'ignore_severity': 3, 'hush_until': seven_days_hence } | to_json }}"
        api_key: "{{ crm_api_key }}"
        key: "{{ crm_site_key }}"
      body_format: form-urlencoded
      url_username: "{{ (env == 'Test') | ternary('megaphone', '') }}"
      url_password: "{{ (env == 'Test') | ternary('megaphone', '') }}"
    with_items:
      - checkVersion_upgrade
      - checkVersion_patch
    delegate_to: 127.0.0.1
    when: civicrm == 'Yes'
    tags: civi-core

  - name: Collect last 10 errors in watchdog
    shell: "PATH=$HOME/bin:$PATH;drush --root='{{ webroot }}' watchdog:show --severity=3"
    when: cms == 'Drupal' or cms == 'Drupal8'
    register: drushmessages
    tags: clear-drush, show-drush
    changed_when: false
  
  - name: Show last 10 errors in watchdog
    debug:
      var: drushmessages.stdout
    tags: clear-drush, show-drush
    changed_when: false

  - name: Clear errors in watchdog
    shell: "PATH=$HOME/bin:$PATH;drush --yes --root='{{ webroot }}' watchdog:delete --severity=3"
    when: cms == 'Drupal' or cms == 'Drupal8' and drushmessages.stdout != ''
    tags: clear-drush
