---
- hosts: mayfirst_ng,mayfirst_ng_site
  become: no
  gather_facts: no
  roles:
    - { role: mayfirst, tags: always}

- hosts: websites
  become: "{{ 'no' if run_as_user == ansible_user else ('no' if 'mayfirst_ng_site' in group_names else 'yes') }}"
  roles:
    - { role: site-db-sync, tags: [site-db-sync] }
