---
# This provisions any VPSes that were defined but not built in server-list
- hosts: all
  become: yes

  tasks:
  - debug: var=ansible_hostname
  - debug: var=hostname
  - debug: var=inventory_hostname
