---
- hosts: mayfirst_ng,mayfirst_ng_site
  become: false
  gather_facts: false
  roles:
    - {role: mayfirst, tags: always}

- name: Update sites
  hosts: websites_test:websites_live
  become: "{{ 'false' if run_as_user == ansible_user else ('false' if 'mayfirst_ng_site' in group_names else 'true') }}"
  gather_facts: false

  roles:
    - {role: common_vars, tags: always}
    - {role: update-sites, tags: update-sites}
