---
- name: Run Drupal 8+ upgrades
  hosts: websites_dev:&maintenance_drupal8
  become: "{{ 'no' if run_as_user == ansible_user else 'yes' }}"
  gather_facts: no

  roles:
    - { role: upgrade-drupal, tags: upgrade-drupal, when: contract_type is search("Drupal Maintenance") and freeze_cms != "1"  and cms == 'Drupal8'}

- name: Run Drupal 7 upgrades
  #TODO: at some point this shouldn't just work on localhosts
  hosts: websites_dev:&maintenance_drupal
  become: "{{ 'no' if run_as_user == ansible_user else 'yes' }}"
  gather_facts: no

  roles:
    - { role: upgrade-d7, tags: upgrade-d7, when: contract_type is search("Drupal Maintenance") and freeze_cms != "1"  and cms == 'Drupal'}

- name: Run WordPress upgrades
  #TODO: at some point this shouldn't just work on localhosts
  hosts: websites_dev:&maintenance_wp
  become: "{{ 'no' if run_as_user == ansible_user else 'yes' }}"
  gather_facts: no

  roles:
    - { role: upgrade-wp, tags: upgrade-wp, when: contract_type is search("WordPress Maintenance") and freeze_cms != "1" and cms == 'WordPress' }


- name: Run Civi upgrades
  #TODO: at some point this shouldn't just work on localhosts
  hosts: websites_dev:&maintenance_civi
  become: "{{ 'no' if run_as_user == ansible_user else 'yes' }}"
  gather_facts: no

  roles:
    - { role: upgrade-civi, tags: upgrade-civi, when: contract_type is search("Civi Maintenance") and freeze_crm != "1" and civicrm == 'Yes' }
