---
- name: Run upgrades
  #TODO: at some point this shouldn't just work on localhosts
  hosts: websites-dev
  gather_facts: no

  roles:
    - { role: upgrade-wp, tags: upgrade-wp }
    - { role: upgrade-civi, tags: upgrade-civi }

- name: Update test
  hosts: websites-test

  roles:
    #- { role: vpn-connect, tags: vpn-connect, update-test, update-live }
    - { role: update-sites, tags: update-test }

- name: Update live
  hosts: websites-live

  roles:
    #- { role: vpn-connect, tags: vpn-connect, update-test, update-live }
    - { role: update-sites, tags: update-live}
