---
- name: Update test
  hosts: websites_test

  roles:
    #- { role: vpn-connect, tags: vpn-connect, update-test, update-live }
    - { role: update-sites, tags: update-test }

- name: Update live
  hosts: websites_live

  roles:
    #- { role: vpn-connect, tags: vpn-connect, update-test, update-live }
    - { role: update-sites, tags: update-live}
