---
# This provisions any VPSes that were defined but not built in server-list
- import_playbook: provision.yml
- hosts: vps
  become: yes

  roles:
    - common
    - mtcusers

- hosts: lamp
  become: yes

  roles:
    - { role: firewall-common, tags: firewall }
    - { role: geerlingguy.apache, tags: apache }
    - drush
    - icinga2

- hosts: testgroup
  become: yes
  roles:
    - { role: geerlingguy.php , tags: php }
