---
# This provisions any VPSes that were defined but not built in server-list
- import_playbook: provision.yml
- hosts: vps
  become: yes

  roles:
    - common
    - mtcusers
    - ypsman.ipv6-disable
    - { role: firewall-common, tags: firewall }
    - drush
    - icinga2
