---
# This is so fucking ugly. Newer versions of borgbackup eliminate the need for piping to tail and cut, but we probably won't have them until Debian 10 ships.
- name: Get the latest backup archive name
  shell: borg list --remote-path /usr/local/bin/borg1/borg1 8139@usw-s008.rsync.net:{{ client + '-' + hostname }} | tail -n1 | cut -f 1 -d ' '
  environment:
    BORG_PASSPHRASE: "{{ lookup('passwordstore', client + '/' + hostname + '/borg/remote') }}"
  register: archive_name
  changed_when: false

- debug: var=archive_name

- name: Download the latest copy of the database
  shell: borg extract --strip-components 4 --remote-path /usr/local/bin/borg1/borg1 8139@usw-s008.rsync.net:{{ client + '-' + hostname }}::{{ archive_name }} var/backups/mysql/sqldump
  environment:
    BORG_PASSPHRASE: "{{ lookup('passwordstore', client + '/' + hostname + '/borg/remote') }}"

