---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure backupninja and borgbackup are installed
  apt:
    name: 
      - borgbackup
      - backupninja

- name: Install borgbackup backport (on Debian 8)
  apt:
    name: borgbackup
    default_release: jessie-backports
  when: ansible_distribution == 'Debian' and ansible_distribution_version == '8'

- name: Install the patched MySQL handler
  copy:
    force: yes
    src: files/mysql
    dest: /usr/share/backupninja/mysql

- name: Install the Icinga-aware fork
  copy:
    force: yes
    src: files/backupninja
    dest: /usr/sbin/backupninja

- name: Create a borg repo local to the remote host
  command: borg init /opt/borg
  args:
    creates: /opt/borg/config
  environment:
    BORG_PASSPHRASE: "{{ lookup('passwordstore', client + '/' + hostname + '/borg/local create=true length=32') }}"

- name: Configure backupninja
  template:
    src: "{{ 'templates/' + item + '.j2' }}"
    dest: "{{ '/etc/backup.d/' + item }}"
    mode: 0600
  with_items:
    - 10-info.sys
    - 30-databases.mysql
    - 50-borg-local.sh
    - 60-borg-remote.sh

- name: Configure backupninja.conf with Icinga2
  template:
    src: templates/backupninja.conf.j2
    dest: /etc/backupninja.conf
    mode: 0600
