- name: create a keypair for root
  user:
    name: root
    generate_ssh_key: yes

- name: get the public key
  command: cat /root/.ssh/id_rsa.pub
  register: publickey
  changed_when: false

# If your public key isn't on the rsync.net account this will fail!
- name: get the authorized_keys from rsync.net
  local_action: command ssh 8139@usw-s008.rsync.net cat .ssh/authorized_keys
  register: installed_keys
  become: no
  changed_when: false

- name: Add the public key to the local authorized_keys file
  shell: echo {{ publickey.stdout }} | ssh 8139@usw-s008.rsync.net 'dd of=.ssh/authorized_keys oflag=append conv=notrunc'
  delegate_to: 127.0.0.1
  become: no
  when: publickey.stdout not in installed_keys.stdout_lines

- name: Check if the remote repo exists
  command: ssh 8139@usw-s008.rsync.net ls -l "{{ client + '-' + hostname + '/config' }}"
  register: remoterepo
  changed_when: false
  failed_when: false

  # FIXME: Once Debian 10 ships and we have borgbackup 1.1+ on all systems, change the encryption to blake2b.
- name: Create a borg repo on rsync.net
  command: "borg init 8139@usw-s008.rsync.net:{{ client + '-' + hostname }} -e repokey --remote-path=/usr/local/bin/borg1/borg1"
  environment:
    BORG_PASSPHRASE: "{{ lookup('passwordstore', client + '/' + hostname + '/borg/remote create=true length=32') }}"
  when: remoterepo.rc == 1

