blocked_bots:
  - MJ12bot
  - AhrefsBot
  - dotbot
  - PetalBot
  - SemrushBot
  - MauiBot (crawler.feedback+gamma@gmail.com)
  - SEOkicks-Robot
  - Zoominfobot
  - DataForSeoBot
  - serpstatbot
  - Bytedance
  - Bytespider
  - GPTBot
