rsyncnet_user: "1418"
rsyncnet_server: "usw-s001.rsync.net"
additional_users:
  John:
    name: john
    shell: "/bin/bash"
    groups:
      - www-data
      - ln
      - ln-test
      - ln-2-test
#    password: "{{ lookup('community.general.passwordstore', 'megaphone/ansible/users/noah') }}"
    authorized:
      - https://ssh.megaphonetech.com/john_id_rsa.pub
    hasdotfiles: false
  Peter:
    name: peterh
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
      - ln
    password: "{{ lookup('community.general.passwordstore', 'megaphone/ansible/users/peterh') }}"
    authorized:
      - https://ssh.megaphonetech.com/peterh_id_rsa.pub
    hasdotfiles: false


