- name: restart php-fpm                             
  service:                                          
    name: php7.0-fpm
    state: restarted                                

- name: restart apache
  service:
    name: apache2
    state: restarted
