- name: restart primary icinga
  shell: "service icinga2 checkconfig && service icinga2 restart"
  delegate_to: "{{ primary_icinga_server }}"
  args:
    warn: false

- name: restart satellite icinga
  shell: "service icinga2 checkconfig && service icinga2 restart"
  args:
    warn: false
