linode_api_key: "{{ lookup('passwordstore', '9to5/linode/apikey') }}"
linode_username: 9to5admin

users:
  Jon:
    name: jon
    shell: "/bin/zsh"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/jon') }}"
    authorized:
      - https://ssh.megaphonetech.com/jon_id_rsa.pub
    hasdotfiles: true
    dotfiles: https://github.com/MegaphoneJon/dotfiles.git
  Joseph:
    name: joseph
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/joseph') }}"
    authorized:
      - https://ssh.megaphonetech.com/joseph_id_rsa.pub
    hasdotfiles: false
  Noah:
    name: noah
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/noah') }}"
    authorized:
      - https://ssh.megaphonetech.com/noah_id_rsa.pub
    hasdotfiles: false
  Dana:
    name: dana
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    authorized:
      - https://ssh.megaphonetech.com/dana_id_rsa.pub
    hasdotfiles: false
  Kevin:
    name: kevin
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    authorized:
      - https://ssh.megaphonetech.com/kevin_id_rsa.pub
    hasdotfiles: false

