users:
  Jon:
    name: jon
    shell: "/bin/zsh"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/jon') }}"
    authorized:
      - https://ssh.megaphonetech.com/jon_id_rsa.pub
    hasdotfiles: true
    dotfiles: https://github.com/MegaphoneJon/dotfiles.git
  Joseph:
    name: joseph
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/joseph') }}"
    authorized:
      - https://ssh.megaphonetech.com/joseph_id_rsa.pub
    hasdotfiles: false
  Pete:
    name: petednz
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    authorized:
      - https://ssh.megaphonetech.com/petednz_id_rsa.pub
    hasdotfiles: false
  Jitendra:
    name: jitendra
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    authorized:
      - https://ssh.megaphonetech.com/jitendra_id_rsa.pub
    hasdotfiles: false
  Luke:
    name: luke
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    authorized:
      - https://ssh.megaphonetech.com/luke_id_rsa.pub
    hasdotfiles: false