users:
  Jon:
    name: jon
    shell: "/bin/zsh"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/jon') }}"
    authorized:
      - https://ssh.megaphonetech.com/jon_id_rsa.pub
    hasdotfiles: true
    dotfiles: https://github.com/MegaphoneJon/dotfiles.git
  Joseph:
    name: joseph
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/joseph') }}"
    authorized:
      - https://ssh.megaphonetech.com/joseph_id_rsa.pub
    hasdotfiles: false
  Edsel:
    name: edsel
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/edsel') }}"
    authorized:
      - https://ssh.megaphonetech.com/edsel_id_rsa.pub
    hasdotfiles: false
  Monish:
    name: monish
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/monish') }}"
    authorized:
      - https://ssh.megaphonetech.com/monish_id_rsa.pub
    hasdotfiles: false
  JoeMurray:
    name: joemurray
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    authorized:
      - https://ssh.megaphonetech.com/joemurray_id_rsa.pub
    hasdotfiles: false
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/joemurray') }}"
  Seamus:
    name: seamus
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    authorized:
      - https://ssh.megaphonetech.com/seamus_id_rsa.pub
    hasdotfiles: false
  Brienne:
    name: brienne
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    authorized:
      - https://ssh.megaphonetech.com/brienne_id_rsa.pub
    hasdotfiles: false
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/brienne') }}"
