- name: Catch worker output on php-fpm
  lineinfile:
    dest: "{{ php_fpm_pool_conf_path }}"
    regexp: "^;*catch_workers_output = yes$"
    line: "catch_workers_output = yes"
    state: present
  notify: restart php-fpm
