# Add Megaphone key to root/Ansible user on all servers
- name: Add Megaphone keys to "{{ sshuser }}"
  authorized_key:
    user: "{{ sshuser }}"
    key: "{{ item }}"
  with_file:
    - files/jon_id_rsa.pub
    - files/joseph_id_rsa.pub
  tags: [configuration,users,keys]

- name: Configure the hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }} {{ hostname }}"
  tags: [hostname, configuration]

- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  tags: [hostname, configuration]

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
    # 86400 seconds = 24 hours
    cache_valid_time: 86400
  with_items:
    - acl
    - aptitude
    - apt-show-versions
    - bzip2
    - cron-apt
    - debconf-utils
    - fail2ban
    - git
    - htop
    - iotop
    - iptables-persistent
    - mtr-tiny
    - ncdu
    - nmap
    - ntp
    - screen
    - sudo
    - sysstat
    - tree
    - unzip
    - vim
    - zip
    - zsh
    - silversearcher-ag
   
  tags: [packages, configuration]
  when: ansible_os_family =="Debian"

- name: Set timezone
  timezone:
    name: "{{ timezone }}"
  notify:
    - restart crond
  tags: [timezone, configuration]
