---
- name: Install jessie-backports
  apt_repository: repo="deb http://ftp.debian.org/debian jessie-backports main"
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '8'
  tags: icinga2

- name: Install PPA on xenial
  apt_repository: repo='ppa:formorer/icinga'
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'
  tags: icinga2
  
- name: Install Icinga2 (non-backport)
  apt: name="icinga2" state=present
  when: not(ansible_distribution == 'Debian' and ansible_distribution_major_version == '8')
  tags: icinga2

- name: Install Icinga2 (backport)
  apt: name="icinga2" state=present default_release=jessie-backports
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '8'
  tags: icinga2

# Debian installs some some host definitions that interfere with being a satellite; delete them
- name: remove hosts.conf
  file: path='/etc/icinga2/conf.d/hosts.conf' state=absent
  tags: icinga2

- name: Enable/start Icinga2 in systemd
  systemd: 
    name: icinga2 
    enabled: yes
    state: started
  tags: icinga2

- name: Check if check_apt.orig exists
  stat: path=/usr/lib/nagios/plugins/check_apt.orig
  register: check_apt_orig
  tags: icinga2

- name: Copy check_apt to check_apt.orig
  copy:
    src: /usr/lib/nagios/plugins/check_apt
    dest: /usr/lib/nagios/plugins/check_apt.orig
    remote_src: yes
    force: no
  tags: icinga2

- name: Install updated check_apt
  copy:
    src: files/check_apt
    dest: /usr/lib/nagios/plugins/check_apt
  tags: icinga2
