local_borg_dir: /var/backups/borg
additional_users:
  Noah:
    name: noah
    shell: "/bin/zsh"
    groups:
      - sudo
      - www-data
    password: "{{ lookup('passwordstore', 'megaphone/ansible/users/noah') }}"
    authorized:
      - https://ssh.megaphonetech.com/noah_id_rsa.pub
    hasdotfiles: false
  Dana:
    name: dana
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    authorized:
      - https://ssh.megaphonetech.com/dana_id_rsa.pub
    hasdotfiles: false
  Kevin:
    name: kevin
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
    authorized:
      - https://ssh.megaphonetech.com/kevin_id_rsa.pub
    hasdotfiles: false
