---
- name: Configure /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ bare_url }}"
  tags: [hostname, configuration]
  when: env == 'Dev'
  become: yes

- name: Update MFPL DNS
  local_action: command php "{{ inventory_dir }}/helpers/mfplapi.php" "{{ inventory_hostname }}" "{{ ip_address }}"
  register: dnshelper_result
  #In theory, a better approach is to do a DNS lookup and see if I know how to control that nameserver.
  when: bare_url is search("megaphonetech.com")
  changed_when: "dnshelper_result.stdout != 'DNS already exists and is correct.'"
  become: no
