---
- name: Create the run_as_user
  user:
    name: "{{ run_as_user }}"
    shell: /bin/nologin
    generate_ssh_key: yes
    home: "/home/{{ run_as_user }}"

- name: Get users to add to the new group
  set_fact:
    userlist: "{{ userlist|default([]) + [ item.value.name ] + [ ansible_user ] }}"
  with_dict: "{{ users }}"

- name: Get list of groups to add to users
  set_fact:
    grouplist: "{{ grouplist|default([]) + [ run_as_user ] }}"

- name: Add Megaphone staff to the newly-created group
  user:
    name: "{{ item[0] }}"
    append: yes
    groups:
      - "{{ item[1] }}"
  with_nested:
    - "{{ userlist }}"
    - "{{ grouplist }}"

- name: Create the php-fpm pool directory
  file:
    path: /etc/php/{{ php_version }}/fpm/pool.d/
    state: directory

- name: Create a php-fpm pool
  template:
    src: templates/php-pool.j2
    dest: /etc/php/{{ php_version }}/fpm/pool.d/{{ run_as_user }}.conf
  notify: restart php-fpm

- name: Create vhost conf (Apache)
  template:
    src: templates/vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ bare_url }}.conf
  notify: restart apache

- name: Enable the site (Apache)
  file:
    src: /etc/apache2/sites-available/{{ bare_url }}.conf
    dest: /etc/apache2/sites-enabled/{{ bare_url }}.conf
    state: link
  notify: restart apache
