additional_users:
  Lottie:
    name: lottie
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
      - dev
    authorized:
      - https://ssh.megaphonetech.com/lottie_id_rsa.pub
    hasdotfiles: false
  Mark:
    name: libkuman
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
      - dev
    authorized:
      - https://ssh.megaphonetech.com/libkuman_id_rsa.pub
    hasdotfiles: false
  Guy:
    name: guy
    shell: "/bin/bash"
    groups:
      - sudo
      - www-data
      - dev
    authorized:
      - https://ssh.megaphonetech.com/guy_id_rsa.pub
    hasdotfiles: false
greenlist_ips:
  - 24.73.13.145
