---
#installing all relevant drush versions!
- name: Clone drush from Github
  git:
    repo=https://github.com/drush-ops/drush.git
    dest="/usr/local/src/drush{{ item[0:1] }}"
    version="{{ item }}"
  register: drush_clone
  with_items: "{{ drushversion }}"
  tags: [drush,drupal]

- name: Install Drush dependencies with composer
  shell: >
    /usr/local/bin/composer install --prefer-source --no-interaction
    chdir="/usr/local/src/drush{{ item[0:1] }}"
    creates="/usr/local/src/drush{{ item[0:1] }}/vendor/autoload.php"
  with_items: "{{ drushversion  }}"
  tags: [drush,drupal]

- name: Link drush executable
  file:
    src: "/usr/local/src/drush{{ item[0:1] }}/drush"
    dest: "/usr/local/bin/drush{{ item[0:1] }}"
    state: link
  with_items: "{{ drushversion  }}"
  tags: [drush,drupal]

- name: install Backdrop
  git:
    repo=https://github.com/backdrop-contrib/drush.git
    dest="/usr/local/src/drush8/commands/backdrop"
    version=1.x-0.x
  when: backdrop
  tags: [drush,backdrop]
- name: copy drush Script
  copy: src=files/drush dest=/usr/local/bin/drush mode=0755
  tags: [drush,backdrop]
