rsyncnet_user: "3294"
rsyncnet_server: "usw-s003.rsync.net"

# behe has gitea on port 10022, so let's customize here.
incoming_ports:
  - { port: 22, name: 'SSH' }
  - { port: 80, name: 'HTTP' }
  - { port: 443, name: 'HTTPS' }
  - { port: 5665, name: 'Icinga2' }
  - { port: 10022, name: 'gitea SSH' }

# Custom Icinga2 file
template_src: "files/{{ inventory_hostname }}/templates/icinga2.host.j2"
php_version: '7.3'
php_packages_extra:
  - php-pear
  - php-imagick
  - php{{ php_version }}-bz2
  - php{{ php_version }}-cli
  - php{{ php_version }}-curl
  - php{{ php_version }}-fpm
  - php{{ php_version }}-gd
  - php{{ php_version }}-imap
  - php{{ php_version }}-intl
  - php{{ php_version }}-json
  - php{{ php_version }}-ldap
  - php{{ php_version }}-mbstring
  - php{{ php_version }}-mysql
  - php{{ php_version }}-opcache
  - php{{ php_version }}-readline
  - php{{ php_version }}-soap
  - php{{ php_version }}-sqlite3
  - php{{ php_version }}-xml
  - php{{ php_version }}-zip
greenlist_ips:
  - 69.122.128.206
  - 68.192.46.116

