- name: Download wordpress into /srv/wordpress using wp[-cli] command as the wordpress user
  command: "wp core download --path={{ item.item.value.webroot }}"
  args:
    creates: "{{ item.item.value.webroot }}/wp-load.php"

- name: Create wp-config.php
  command: "wp config create --dbname={{ item.item.value.cms_db_name }} --dbuser={{ item.item.value.db_user }} --dbpass={{ lookup('passwordstore', client + '/' + hostname + '/' + item.item.value.bare_url + '/mysql') }} --path={{ item.item.value.webroot }}"
  args:
    creates: "{{ item.item.value.webroot }}/wp-config.php"

- name: Run the WP installer
  command: "wp core install --url={{ item.item.value.bare_url }} --title='{{ item.item.value.site_title }}' --admin_user=admin --admin_email={{ item.item.value.admin_email }} --admin_password={{ lookup('passwordstore', client + '/' + hostname + '/' + item.item.value.bare_url + '/admin create=true length=32') }}  --path={{ item.item.value.webroot }}"
  changed_when: wpinstaller.stdout != "WordPress is already installed."
  register: wpinstaller

- name: Install the wp-login companion plugin
  command: "wp login install --activate --path={{ item.item.value.webroot }}"
  args:
    creates: "{{ item.item.value.webroot }}/wp-content/plugins/wp-cli-login-server"

- name: Check out civicrm-setup
  git:
    repo: https://github.com/civicrm/civicrm-setup
    dest: /opt/civicrm-setup
  become_user: root
  when: item.item.value.civicrm == 'Yes'

- name: Download the latest tarball
  get_url:
    url: https://download.civicrm.org/latest/civicrm-STABLE-wordpress.zip
    dest: /tmp/civicrm-STABLE-wordpress.zip
  when: item.item.value.civicrm == 'Yes'

- name: Create CiviCRM folder
  file:
    path: "{{ item.item.value.civiroot }}"
    state: directory
  when: item.item.value.civicrm == 'Yes'

- name: Unzip the tarball
  unarchive:
    src: /tmp/civicrm-STABLE-wordpress.zip
    dest: "{{ item.item.value.civiroot }}/../.."
    remote_src: yes
    creates: "{{ item.item.value.civiroot }}/composer.json"
  when: item.item.value.civicrm == 'Yes'

- name: Create CiviCRM uploads folder
  file:
    path: "{{ item.item.value.civicrm_settings_php_path }}"
    state: directory
  when: item.item.value.civicrm == 'Yes'

- name: Set the WP .gitignore
  copy:
    src: files/wp-gitignore
    dest: "{{ item.item.value.webroot }}/.gitignore"
