- debug: msg="{{ item.item.value.webroot }}/wp-load.php"
- name: Download wordpress into /srv/wordpress using wp[-cli] command as the wordpress user
  command: "wp core download --path={{ item.item.value.webroot }}"
  args:
    creates: "{{ item.item.value.webroot }}/wp-load.php"

- name: Create wp-config.php
  command: "wp config create --dbname={{ item.item.value.cms_db_name }} --dbuser={{ item.item.value.db_user }} --dbpass={{ lookup('passwordstore', client + '/' + hostname + '/' + item.item.value.bare_url + '/mysql') }} --path={{ item.item.value.webroot }}"
  args:
    creates: "{{ item.item.value.webroot }}/wp-config.php"

- name: Run the WP installer
  command: "wp core install --url={{ item.item.value.bare_url }} --title='{{ item.item.value.site_title }}' --admin_user=admin --admin_email={{ item.item.value.admin_email }} --admin_password={{ lookup('passwordstore', client + '/' + hostname + '/' + item.item.value.bare_url + '/admin create=true length=32') }}  --path={{ item.item.value.webroot }}"
  changed_when: wpinstaller.stdout != "WordPress is already installed."
  register: wpinstaller

- name: Install the wp-login companion plugin
  command: "wp login install --activate --path={{ item.item.value.webroot }}"
  args:
    creates: "{{ item.item.value.webroot }}/wp-content/plugins/wp-cli-login-server"

- name: Check out civicrm-setup
  git:
    repo: https://github.com/civicrm/civicrm-setup
    dest: /opt/civicrm-setup
  become_user: root
  when: item.item.value.civicrm == 'Yes'

- name: Check out CiviCRM from git
  git:
    repo: https://github.com/civicrm/civicrm-core.git
    dest: "{{ item.item.value.webroot }}/wp-content/plugins/civicrm/civicrm"
  when: item.item.value.civicrm == 'Yes'

- name: Create CiviCRM uploads folder
  file:
    path: "{{ item.item.value.civicrm_settings_php_path }}"
    state: directory

- name: Template out civicrm.settings.php
  template:
    src: civicrm.settings.j2
    dest: "{{ item.item.value.civicrm_settings_php_path }}/civicrm.settings.php"
    owner: "{{ ansible_user }}"
    group: "{{ item.item.value.run_as_user }}"
    mode: 0660
  become_user: root
  when: item.item.value.civicrm == 'Yes'
#TODO: git init, commit, maybe .gitignore tweak and permissions fixed?
#TODO: CiviCRM.  Is cv:install useful here?
