- debug: msg="{{ item.item.value.webroot }}/wp-load.php"
- name: Download wordpress into /srv/wordpress using wp[-cli] command as the wordpress user
  command: "wp core download --path={{ item.item.value.webroot }}"
  args:
    creates: "{{ item.item.value.webroot }}/wp-load.php"

- name: Create wp-config.php
  command: "wp config create --dbname={{ item.item.value.cms_db_name }} --dbuser={{ item.item.value.db_user }} --dbpass={{ lookup('passwordstore', client + '/' + hostname + '/' + item.item.value.bare_url + '/mysql') }} --path={{ item.item.value.webroot }}"
  args:
    creates: "{{ item.item.value.webroot }}/wp-config.php"

- name: Run the WP installer
  command: "wp core install --url={{ item.item.value.bare_url }} --title='{{ item.item.value.site_title }}' --admin_user=admin --admin_email={{ item.item.value.admin_email }} --admin_password={{ lookup('passwordstore', client + '/' + hostname + '/' + item.item.value.bare_url + '/admin create=true length=32') }}  --path={{ item.item.value.webroot }}"
  changed_when: wpinstaller.stdout != "WordPress is already installed."
  register: wpinstaller

- name: Install the wp-login companion plugin
  command: "wp login install --activate --path={{ item.item.value.webroot }}"
  args:
    creates: "{{ item.item.value.webroot }}/wp-content/plugins/wp-cli-login-server"
#TODO: Finish install https://blog.sucuri.net/2015/08/wp-cli-guide-installing-wordpress.html
#TODO: git init, commit, maybe .gitignore tweak and permissions fixed?
#TODO: CiviCRM.  Is cv:install useful here?
